version: "3.9"
services:
  mysql:
    image: mysql:7.5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./.srv/database:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD: wordpress
      - MYSQL_DATABASE: my-site
      - MYSQL_USER: wordpress
      - MYSQL_USER_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8000:80
    restart: always
    environment:
      - WORDPRES_DB_HOST: mysql:3306
      - WORDPRESS_DB_USER: wordpress
      - WORDPRESS_DB_PASSWORD: wordpress
      - WORDPRESS_DB_NAME: my-site
      - WORDPRESS_DEBUG: 1
    volumes:
      - "./.srv/wordpress:/var/www/html"
